Associate ingredients with recipes via joint table
CraftAcademy/recipe_hub_api pull request #7
Opened 2022-02-08 16:58 UTC by DefyCab

**This PR contains**

-add joint table ingredients_recipes
-add ingredients_recipe model
-update specs 

https://www.pivotaltracker.com/story/show/181184716

@giacoletti @Mljungho @elvitak

2022-02-08 17:15 UTC, Mljungho reviewed
As much as it pains me to say it, I can't find any misstake with this PR. 

@elvitak Have a look, and unless you find anything you can approve :1st_place_medal:

![joke-life-motto](https://user-images.githubusercontent.com/92157834/153039927-30a00ebe-ce96-422a-8377-0ca2f5456362.jpg)

2022-02-09 10:14 UTC, giacoletti requested changes

2022-02-09 10:14 UTC, giacoletti commented on app/models/recipe.rb
> +  # has_many :ingr, through: :ingredients, source: :ingredient
remove commented code

2022-02-09 10:18 UTC, giacoletti commented
Looks good

2022-02-09 10:18 UTC, merged